AWSTemplateFormatVersion: 2010-09-09
Description: CFN Template to create and deploy the TubTub app infrastructure

Parameters:

  # General params
  AppName:
    Type: String
    Description: Application's name

  EnvName:
    Type: String
    Description: Environment name
  
  # ECS params
  AppContainerImage:
    Type: String
    Description: Container repo image name

  TaskDefinitionCpu:
    Type: String
    Description: CPU Size
    Default: "256"

  TaskDefinitionMemory:
    Type: String
    Description: Memory Size
    Default: "512"

  CpuArchitecture:
    Type: String
    Description: CPU Architecture of task definition
    Default: ARM64

  OperatingSystemFamily:
    Type: String
    Description: OS of task definition
    Default: LINUX

  # EventBridge scheduler params
  ScheduledRemindersFrequencyInHours:
    Type: String
    Description: The schedule expression for the notification frequency
    Default: cron(0 * * * *)

  IsScheduledRemindersEnabled:
    Type: String
    AllowedValues:
      - DISABLED
      - ENABLED
    Default: ENABLED
    Description: Flag to enable or disable scheduled reminders

  ScheduledRemindersRuleDescription:
    Type: String
    Description: Description for the scheduled reminders rule

  # VPC params
  EcsTaskSubnetIds:
    Type: String
    Description: Comma separated string of subnet IDs
  
  EcsTaskSecurityGroupIds:
    Type: String
    Description: Comma separated string of security group IDs

  # DynamoDB params
  PrimaryKeyName:
    Type: String
    Description: Name of primary key
    Default: PK

  SecondaryKeyName:
    Type: String
    Description: Name of secondary key
    Default: SK

Resources:

# ---------------------------------------------------------------
#                            EventBridge
# ---------------------------------------------------------------

  # IAM
  RemindersMessagesSchedulerPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub ${EnvName}_${AppName}_reminders_messages_policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - ecs:RunTask
            Resource:
              - !GetAtt EcsTaskDefinition.TaskDefinitionArn
              - !Join [ ":", [ !GetAtt EcsTaskDefinition.TaskDefinitionArn, "*" ] ]
            Condition:
              ArnLike:
                "ecs:Cluster": !GetAtt EcsCluster.Arn
          - Effect: Allow
            Action:
              - iam:PassRole
            Resource: "*"
            Condition:
              StringLike:
                "iam:PassedToService": "ecs-tasks.amazonaws.com"

  RemindersMessagesSchedulerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EnvName}_${AppName}_reminders_messages_role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Ref RemindersMessagesSchedulerPolicy

  RemindersMessagesScheduler:
    Type: AWS::Events::Rule
    Properties:
      Description: !Ref ScheduledRemindersRuleDescription
      State: !Ref IsScheduledRemindersEnabled
      ScheduleExpression: !Ref ScheduledRemindersFrequencyInHours
      Targets:
        - Arn: !GetAtt EcsCluster.Arn
          RoleArn: !GetAtt RemindersMessagesSchedulerRole.Arn
          Id: RemindersCronTask
          EcsParameters:
            TaskDefinitionArn: !GetAtt EcsTaskDefinition.TaskDefinitionArn
            NetworkConfiguration:
              AwsVpcConfiguration:
                SecurityGroups: !Split [ ",", !Ref EcsTaskSecurityGroupIds ]
                Subnets: !Split [ ",", !Ref EcsTaskSubnetIds ]
            LaunchType: FARGATE
            EnableExecuteCommand: true

# ---------------------------------------------------------------
#                             DynamoDB
# ---------------------------------------------------------------

  # DynamoDB
  EndUsersDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${EnvName}_${AppName}_end_user_table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: !Ref PrimaryKeyName
          KeyType: HASH
        - AttributeName: !Ref SecondaryKeyName
          KeyType: RANGE
      ResourcePolicy:
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                AWS: !GetAtt EcsTaskExecutionRole.Arn
              Action:
                - dynamodb:Query
                - dynamodb:UpdateItem
                - dynamodb:BatchWriteItem
              Resource: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${EnvName}_${AppName}_end_user_table

# ---------------------------------------------------------------
#                               ECS
# ---------------------------------------------------------------

  # IAM
  EcsDynamodbReadWritePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub ${EnvName}_${AppName}_ecs_dynamodb_read_write_policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:Query
              - dynamodb:UpdateItem
              - dynamodb:BatchWriteItem
            # Avoided doing !GetAtt EndUsersDataTable.Arn below to avoid circular dependency issues
            Resource: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${EnvName}_${AppName}_end_user_table

  EcsTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EnvName}_${AppName}_ecs_task_esecution_role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Ref EcsDynamodbReadWritePolicy
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  # ECS
  EcsCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${EnvName}_${AppName}_ecs_cluster
      CapacityProviders:
        - FARGATE_SPOT
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE_SPOT
          Weight: 1
      Configuration:
        ExecuteCommandConfiguration:
          Logging: DEFAULT

  EcsTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Cpu: !Ref TaskDefinitionCpu
      Memory: !Ref TaskDefinitionMemory
      NetworkMode: awsvpc
      ExecutionRoleArn: !GetAtt EcsTaskExecutionRole.Arn
      TaskRoleArn: !GetAtt EcsTaskExecutionRole.Arn
      RequiresCompatibilities:
        - FARGATE
      RuntimePlatform:
        CpuArchitecture: !Ref CpuArchitecture
        OperatingSystemFamily: !Ref OperatingSystemFamily
      ContainerDefinitions:
        - Essential: true
          Image: !Ref AppContainerImage
          LogConfiguration: 
            LogDriver: awslogs
            Options: 
              awslogs-group : !Sub /ecs/${EnvName}/${AppName}
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: /cron-task/reminders-service/
          Name: !Sub ${EnvName}_${AppName}_tubtub_reminders_service
          Environment:
            - Name: endusers_datatable_name
              Value: !Ref EndUsersDataTable
            - Name: endusers_datatable_primary_key_name
              Value: !Ref PrimaryKeyName
            - Name: endusers_datatable_secondary_key_name
              Value: !Ref SecondaryKeyName